# Project | Data Scraping, Cleaning, and Merging
### Emily Nell, Chaitanya Patel, Emily Sanders

---

In [1]:
import pandas as pd
import numpy as np
import os
from selenium import webdriver
from selenium.webdriver.common.by import By # used to import different ways to access data in the XML or HTML file
from selenium.webdriver.chrome.service import Service # no longer need to download a driver file, use service
from webdriver_manager.chrome import ChromeDriverManager # used to manage the Chrome driver to emulate a Chrome web browser
from selenium import webdriver

import time
import random
import datetime

---
### Scrape and Clean NCAA football data from BetIQ wesbite from seasons 2021-2024

In [ ]:
# initial scraping of 2024 season
# URL of the College Football Win-Loss Records & Trends Website
url = 'https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/'

# Extract tables from the webpage
tables = pd.read_html(url)

# First table is one with data needed for project
df_win_loss_trends_24 = tables[0]

# Display the DataFrame
df_win_loss_trends_24

              Team Win-Loss Record  Win %   MOV  ATS +/-
0           Oregon          13-1-0  92.9%  15.4     -2.3
1       Notre Dame          14-2-0  87.5%  20.6      9.3
2          Ohio St          14-2-0  87.5%  22.8      3.0
3         Boise St          12-2-0  85.7%  14.7      0.9
4             Army          12-2-0  85.7%  15.6      5.5
..             ...             ...    ...   ...      ...
129     Florida St          2-10-0  16.7% -12.6    -10.8
130    Kennesaw St          2-10-0  16.7% -14.7      0.2
131  S Mississippi          1-11-0   8.3% -22.5     -9.0
132         Purdue          1-11-0   8.3% -24.2    -11.2
133        Kent St          0-12-0   0.0% -30.2     -9.4

[134 rows x 5 columns]

In [4]:
# clean 2024 scraped dataframe
df_win_loss_trends_24.sort_values(by="Team", ascending=True, inplace=True)
df_win_loss_trends_24.rename(columns={'Win-Loss Record': 'W-L'}, inplace=True)
df_win_loss_trends_24['Season'] = 2024

df_win_loss_trends_24

            Team    W-L  Win %   MOV  ATS +/-  Season
96     Air Force  5-7-0  41.7%  -4.3     -1.8    2024
108        Akron  4-8-0  33.3% -11.6     -0.4    2024
29       Alabama  9-4-0  69.2%  16.4     -1.2    2024
82     App State  5-6-0  45.5%  -6.3     -6.9    2024
107      Arizona  4-8-0  33.3% -10.0    -13.3    2024
..           ...    ...    ...   ...      ...     ...
100  Wake Forest  4-8-0  33.3%  -6.8     -2.7    2024
48    Wash State  8-5-0  61.5%   6.7     -1.2    2024
74    Washington  6-7-0  46.2%  -0.4     -3.5    2024
92     Wisconsin  5-7-0  41.7%  -0.5     -1.3    2024
116      Wyoming  3-9-0  25.0%  -9.0     -1.5    2024

[134 rows x 6 columns]

In [5]:
# scrape remaining seasons (2021-2023)
season = 2021
url_org = 'https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/?season=2021'
specific_columns = []

page_counter = 1
df_win_loss_trends = []
seq_start = 2021
end_condition = 2023


options = webdriver.FirefoxOptions()
browser = webdriver.Firefox(options=options)

while seq_start <= end_condition:
    url = 'https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/?season=' + str(season)
    print(url)

    current_year = season 
    season += 1
    browser.get(url)
    time.sleep(random.uniform(1, 4))

    tables = pd.read_html(browser.page_source)

    if tables:
        df = tables[0]
        df['Season'] = current_year  
        df_win_loss_trends.append(df)
    else:
        print(f"No table found on {url}")

    time.sleep(random.uniform(1, 4))
    seq_start += 1 

browser.quit()

# Concatenate all the DataFrames in the list
df_win_loss_trends = pd.concat(df_win_loss_trends, ignore_index=True)

df_win_loss_trends

https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/?season=2021

C:\Users\nelle\AppData\Local\Temp\ipykernel_31500\2961900348.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(browser.page_source)

https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/?season=2022

C:\Users\nelle\AppData\Local\Temp\ipykernel_31500\2961900348.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(browser.page_source)

https://betiq.teamrankings.com/college-football/betting-trends/win-loss-records/?season=2023

C:\Users\nelle\AppData\Local\Temp\ipykernel_31500\2961900348.py:24: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(browser.page_source)

            Team Win-Loss Record  Win %   MOV  ATS +/-  Season
0        Georgia          14-1-0  93.3%  28.4      7.3    2021
1     Cincinnati          13-1-0  92.9%  20.0      2.7    2021
2      Louisiana          13-1-0  92.9%  12.6      2.9    2021
3        Alabama          13-2-0  86.7%  19.7     -2.5    2021
4       Michigan          12-2-0  85.7%  18.4      8.8    2021
..           ...             ...    ...   ...      ...     ...
395        Akron          2-10-0  16.7% -11.8     -5.5    2023
396       Nevada          2-10-0  16.7% -16.1     -2.1    2023
397   Vanderbilt          2-10-0  16.7% -13.3     -4.3    2023
398      Kent St          1-11-0   8.3% -19.9     -5.2    2023
399  Kennesaw St           0-1-0   0.0%  -3.0     13.0    2023

[400 rows x 6 columns]

In [32]:
df_win_loss_trends.rename(columns={'Win-Loss Record': 'W-L'}, inplace=True)

In [33]:
final_df_win_loss_trends = pd.concat([df_win_loss_trends, df_win_loss_trends_24])

final_df_win_loss_trends.sort_values(by="Team", ascending=True, inplace=True)

final_df_win_loss_trends['W-L'] = final_df_win_loss_trends['W-L'].apply(lambda wl: wl[:-2] if wl.endswith('-0') else wl)
final_df_win_loss_trends[['Wins', 'Losses']] = final_df_win_loss_trends['W-L'].str.split('-', expand=True)
final_df_win_loss_trends['Wins'] = final_df_win_loss_trends['Wins'].astype(int)
final_df_win_loss_trends['Losses'] = final_df_win_loss_trends['Losses'].astype(int)
final_df_win_loss_trends = final_df_win_loss_trends.drop(columns='W-L')

final_df_win_loss_trends['Win %'] = final_df_win_loss_trends['Win %'].str.rstrip('%')
final_df_win_loss_trends['Win %'] = final_df_win_loss_trends['Win %'].astype(float)

final_df_win_loss_trends

          Team  Win %   MOV  ATS +/-  Season  Wins  Losses
22   Air Force   76.9  11.2      3.3    2021    10       3
96   Air Force   41.7  -4.3     -1.8    2024     5       7
147  Air Force   76.9  14.5      2.2    2022    10       3
300  Air Force   69.2   9.7     -2.7    2023     9       4
108      Akron   33.3 -11.6     -0.4    2024     4       8
..         ...    ...   ...      ...     ...   ...     ...
92   Wisconsin   41.7  -0.5     -1.3    2024     5       7
200    Wyoming   53.9  -2.7      0.4    2022     7       6
303    Wyoming   69.2   3.0      2.1    2023     9       4
51     Wyoming   53.9   1.7     -3.5    2021     7       6
116    Wyoming   25.0  -9.0     -1.5    2024     3       9

[534 rows x 7 columns]

In [34]:
final_df_win_loss_trends.to_csv('NCAA_football_win_loss_trends.csv', index=False)

---
### Upload NCAA_stats.csv from NCAA_first_scrape.ipynb as a dataframe and merge with NCAA_football_win_loss_trends.csv

In [35]:
ncaa_stats_final = pd.read_csv('NCAA_stats.csv')
ncaa_stats_final

,Offensive Rank,Team,G,Offense TDs,Total Offense YPG,Season,Rushing Rank,Rushing TDs,Rush YPG,Passing Rank,...,Penalties,Penalties Per Game,Penalty YPG Rank,Penalty YPG,TOP Rank,Avg Time of Possession,ATP Rank,Conference,Wins,Losses
0,1,Miami (FL),13,71,537.2,2024,31,30,188.9,3,...,86,6.62,119,67.54,8.0,32:43,NaN,ACC,10,3
1,2,Ole Miss,13,60,526.5,2024,44,29,175.7,2,...,94,7.23,127,72.00,108.0,28:23,NaN,SEC,10,3
2,3,North Texas,13,57,488.8,2024,69,24,160.6,4,...,91,7.00,98,59.46,128.0,26:47,NaN,The American,6,7
3,4,New Mexico,12,49,484.3,2024,2,37,253.6,61,...,112,9.33,132,81.50,98.0,28:53,NaN,Mountain West,5,7
4,5,Texas St.,13,58,476.9,2024,15,27,208.2,22,...,88,6.77,114,64.15,34.0,31:12,NaN,Sun Belt,8,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,126,Navy,12,25,282.3,2021,9,19,225.5,130,...,53,4.42,6,36.17,NaN,34:48,5.0,AAC,4,8
519,127,Southern Miss.,12,22,266.3,2021,109,8,120.8,125,...,98,8.17,101,62.50,NaN,30:29,46.0,CUSA,3,9
520,128,UConn,12,19,265.0,2021,122,8,100.8,116,...,81,6.75,49,49.17,NaN,25:49,129.0,FBS Independent,1,11
521,129,Colorado,12,22,257.4,2021,98,12,126.2,126,...,76,6.33,78,56.42,NaN,27:12,122.0,Pac-12,4,8
522,130,New Mexico,12,15,234.9,2021,108,5,120.8,127,...,83,6.92,82,57.08,NaN,29:52,65.0,Mountain West,3,9

In [36]:
# clean team name for merging
def clean_team_name_simple(name):
    name = name.lower()  
    name = name.replace('&', 'and')
    name = name.replace('.', '')
    name = name.replace(',', '')
    name = name.replace("'", '')
    name = name.replace('-', ' ')
    name = name.strip()
    name = ' '.join(name.split())  
    name = name.title()  
    return name

ncaa_stats_final['Team'] = ncaa_stats_final['Team'].apply(clean_team_name_simple)
final_df_win_loss_trends['Team'] = final_df_win_loss_trends['Team'].apply(clean_team_name_simple)

In [ ]:
# name map the rest of the teams that did not make it through clean_team_name_simple application
name_map = {
    'Army West Point': 'Army',
    'Boston College': 'Boston Col',
    'Bowling Green': 'Bowling Grn',
    'Coastal Carolina': 'Coastal Car',
    'East Carolina': 'E Carolina',
    'Eastern Mich': 'E Michigan',
    'Fiu': 'Florida Intl',
    'Georgia Tech': 'Ga Tech',
    'Jacksonville St': 'Jksnville St',
    'James Madison': 'James Mad',
    'Louisiana Tech': 'La Tech',
    'Miami (Fl)': 'Miami',
    'Mississippi St': 'Miss State',
    'Ole Miss': 'Mississippi',
    'North Carolina': 'N Carolina',
    'Niu': 'N Illinois',
    'New Mexico St': 'N Mex State',
    'Sam Houston': 'Sam Hous St',
    'Smu': 'S Methodist',
    'South Alabama': 'S Alabama',
    'South Carolina': 'S Carolina',
    'South Fla': 'S Florida',
    'Southern California': 'S California',
    'Southern Miss': 'S Mississippi',
    'Virginia Tech': 'Va Tech',
    'Washington St': 'Wash State',
    'West Virginia': 'W Virginia',
    'Western Ky': 'W Kentucky',
    'Western Mich': 'W Michigan',
    'Massachusetts': 'U Mass',
    'S California': 'Usc',
    'Tcu': 'Tx Christian',
    'Uconn': 'Connecticut',
    'Ulm': 'Ul Monroe',
    'Utep': 'Tx El Paso'
}

ncaa_stats_final['Team'] = ncaa_stats_final['Team'].replace(name_map)

In [51]:
merged_ncaa_stats = pd.merge(ncaa_stats_final, final_df_win_loss_trends, on=['Team', 'Season', 'Wins', 'Losses'], how='inner')
merged_ncaa_stats

,Offensive Rank,Team,G,Offense TDs,Total Offense YPG,Season,Rushing Rank,Rushing TDs,Rush YPG,Passing Rank,...,Penalty YPG,TOP Rank,Avg Time of Possession,ATP Rank,Conference,Wins,Losses,Win %,MOV,ATS +/-
0,1,Miami,13,71,537.2,2024,31,30,188.9,3,...,67.54,8.0,32:43,NaN,ACC,10,3,76.9,18.6,1.2
1,2,Mississippi,13,60,526.5,2024,44,29,175.7,2,...,72.00,108.0,28:23,NaN,SEC,10,3,76.9,24.2,4.5
2,3,North Texas,13,57,488.8,2024,69,24,160.6,4,...,59.46,128.0,26:47,NaN,The American,6,7,46.2,-0.6,-0.4
3,4,New Mexico,12,49,484.3,2024,2,37,253.6,61,...,81.50,98.0,28:53,NaN,Mountain West,5,7,41.7,-4.5,0.7
4,5,Texas St,13,58,476.9,2024,15,27,208.2,22,...,64.15,34.0,31:12,NaN,Sun Belt,8,5,61.5,12.0,-1.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
518,126,Navy,12,25,282.3,2021,9,19,225.5,130,...,36.17,NaN,34:48,5.0,AAC,4,8,33.3,-8.2,2.4
519,127,S Mississippi,12,22,266.3,2021,109,8,120.8,125,...,62.50,NaN,30:29,46.0,CUSA,3,9,25.0,-10.3,-1.5
520,128,Connecticut,12,19,265.0,2021,122,8,100.8,116,...,49.17,NaN,25:49,129.0,FBS Independent,1,11,8.3,-22.9,-1.5
521,129,Colorado,12,22,257.4,2021,98,12,126.2,126,...,56.42,NaN,27:12,122.0,Pac-12,4,8,33.3,-7.9,-0.7
522,130,New Mexico,12,15,234.9,2021,108,5,120.8,127,...,57.08,NaN,29:52,65.0,Mountain West,3,9,25.0,-16.3,-6.8

In [54]:
merged_ncaa_stats.to_csv("merged_NCAA_football_stats.csv", index=False)